[[edge]]
from = "ui-6e16"
to = "ui-1466"
kind = "blocks"
created_at = "2026-10-03T01:32:09.029Z"

[[edge]]
from = "ui-6e16"
to = "ui-9f72"
kind = "blocks"
created_at = "2026-10-03T01:32:09.062Z"

[[edge]]
from = "ui-1466"
to = "ui-8a8c"
kind = "blocks"
created_at = "2026-10-03T01:32:09.110Z"
