[[tier]]
tasks = ["ui-6e16"]

[[tier]]
tasks = [
    "ui-1466",
    "ui-9f72",
]

[[tier]]
tasks = ["ui-8a8c"]

[[tier]]
tasks = ["ui-yj6m"]

[[tier]]
tasks = ["ui-k9a8"]

[[tier]]
tasks = ["ui-4u8g"]

[[tier]]
tasks = ["ui-qbbk"]

[[tier]]
tasks = ["ui-mbhk"]
